- name: Install Clickhouse
  hosts: clickhouse
  roles: 
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector

- name: Install lighthouse
  hosts: lighthouse
  roles: 
    - nginx
    - lighthouse
